version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
      - npm install -g typescript

  pre_build:
    commands:
      - npm run build

  build:
    commands:
      - echo Build complete!
      - ls Build

artifacts:
  files:
    - './**/*'
  base-directory: public