version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
      - npm install -g typescript

  pre_build:
    commands:
      - npm run build
      
  build:
    commands:
      - echo Build complete!

artifacts:
  files:
    - .platform/**
    - Build/**
    - package.json
    - package-lock.json